-- database name "lacus"
-- Ya esta
CREATE TABLE
  "imagen_producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" varchar(255) NOT NULL,
    "secure_url" varchar(500) NOT NULL,
    "id_producto" integer NOT NULL
  );
-- Ya esta
CREATE TABLE
  "tipo_entrega" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(50) UNIQUE NOT NULL
  );

INSERT INTO
  "tipo_entrega" ("nombre")
VALUES
  ('tienda'),
  ('delivery');

CREATE TABLE
  "tarifa_cobertura" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "direccion" varchar(255) UNIQUE NOT NULL,
    "punto_direccion" point NOT,
    "centro_cobertura" point NOT NULL,
    "radio_cobertura" float NOT NULL DEFAULT 0,
    "tarifa_kg_km" decimal(10, 2) NOT NULL DEFAULT 0,
    "tarifa_minima" decimal(10, 2) NOT NULL DEFAULT 0
  );

-- Ya esta
CREATE TABLE
  "producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "codigo" varchar(36) UNIQUE NOT NULL,
    "nombre" varchar(255) UNIQUE NOT NULL,
    "descripcion" text DEFAULT 'Descripción...',
    "peso_kg" float NOT NULL DEFAULT 0,
    "precio" decimal(10, 2) NOT NULL DEFAULT 0,
    "habilitado" bool NOT NULL DEFAULT true,
    "porcentaje_descuento" integer NOT NULL DEFAULT 0,
    "id_categoria" integer NOT NULL DEFAULT 1,
    "id_marca" integer NOT NULL DEFAULT 1
  );
-- Ya esta
CREATE TABLE
  "categoria" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(100) UNIQUE NOT NULL,
    "habilitado" bool DEFAULT true,
    "public_id" varchar(255) NOT NULL,
    "secure_url" varchar(500) NOT NULL
  );
-- Ya esta
CREATE TABLE
  "marca" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(100) UNIQUE NOT NULL,
    "habilitado" bool DEFAULT true,
    "public_id" varchar(255) NOT NULL,
    "secure_url" varchar(500) NOT NULL
  );

-- Ya esta
CREATE TABLE
  "publicacion" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "titulo" varchar(100) UNIQUE NOT NULL,
    "url_redireccion" varchar(500),
    "public_id" varchar(255) NOT NULL,
    "secure_url" varchar(500) NOT NULL
  );

-- Ya esta
CREATE TABLE
  "usuario" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sub" varchar(36) UNIQUE NOT NULL,
    "nombre" varchar(100) NOT NULL,
    "apellido" varchar(100) NOT NULL,
    "dni" varchar(15) NULL,
    "numero" varchar(20) NULL,
    "correo" varchar(255) UNIQUE NOT NULL,
    "habilitado" bool NOT NULL DEFAULT true,
    "id_tipo_usuario" integer NOT NULL DEFAULT 2
  );

-- Ya esta
CREATE TABLE
  "tipo_usuario" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(50) UNIQUE NOT NULL
  );

INSERT INTO
  "tipo_usuario" ("nombre")
VALUES
  ('administrador'),
  ('cliente');

-- ya esta
CREATE TABLE
  "entrada" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "fecha" date NOT NULL,
    "hora" time NOT NULL,
    "habilitado" bool DEFAULT true
  );

-- ya esta
CREATE TABLE
  "detalle_entrada" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" integer NOT NULL DEFAULT 1,
    "id_producto" integer NOT NULL,
    "id_entrada" integer NOT NULL
  );

-- ya esta
CREATE TABLE
  "carrito" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "updated_at" timestamp NOT NULL,
    "id_usuario" integer UNIQUE NOT NULL
  );
-- ya esta
CREATE TABLE
  "detalle_carrito" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cantidad" integer NOT NULL DEFAULT 1,
    "id_producto" integer NOT NULL,
    "id_carrito" integer NOT NULL
  );

-- ya esta
CREATE TABLE
  "pedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "codigo" varchar(36) UNIQUE NOT NULL,
    "fecha" date NOT NULL,
    "hora" time NOT NULL,
    "total" decimal(10, 2) NOT NULL DEFAULT 0,
    "direccion" point,
    "ultima_fecha" date,
    -- 
    "id_estado_pedido" integer NOT NULL DEFAULT 1, 
    -- 
    "id_tipo_entrega" integer NOT NULL DEFAULT 1,
    -- 
    "id_metodo_pago" integer NOT NULL,
    "id_usuario" integer NOT NULL
  );

-- ya esta
CREATE TABLE
  "detalle_pedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "precio" decimal(10, 2) NOT NULL,
    "cantidad" integer NOT NULL DEFAULT 1,
    "subtotal" decimal(10, 2) NOT NULL,
    "id_producto" integer NOT NULL,
    "id_pedido" integer NOT NULL
  );

-- ya esta
CREATE TABLE
  "metodo_pago" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(50) UNIQUE NOT NULL
  );

INSERT INTO
  metodo_pago (nombre)
VALUES
  ('tarjeta'),
  ('yape');

-- ya esta
CREATE TABLE
  "estado_pedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(50) UNIQUE NOT NULL
  );

INSERT INTO
  estado_pedido (nombre)
VALUES
  ('pagado'),
  ('alistado'),
  ('en camino'),
  ('entregado'),
  ('no entregado');

-- ya esta
CREATE TABLE
  "comprobante" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "comprobante" varchar(500)  NULL,
    "xml" varchar(500) NULL,
    "cdr" varchar(500) NULL,
    "id_tipo_comprobante" integer NOT NULL,
    "id_pedido" integer UNIQUE NOT NULL
  );

-- ya esta
CREATE TABLE
  "tipo_comprobante" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" varchar(50) UNIQUE NOT NULL
  );

INSERT INTO
  tipo_comprobante (nombre)
VALUES
  ('boleta'),
  ('factura'),
  ('ticket');

ALTER TABLE "carrito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id");

ALTER TABLE "comprobante" ADD FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id");

ALTER TABLE "imagen_producto" ADD CONSTRAINT "imagen_producto" FOREIGN KEY ("id_producto") REFERENCES "producto" ("id");

ALTER TABLE "producto" ADD CONSTRAINT "producto_categoria" FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id");

ALTER TABLE "producto" ADD CONSTRAINT "producto_marca" FOREIGN KEY ("id_marca") REFERENCES "marca" ("id");

ALTER TABLE "usuario" ADD CONSTRAINT "usuario_tipo_usuario" FOREIGN KEY ("id_tipo_usuario") REFERENCES "tipo_usuario" ("id");

ALTER TABLE "detalle_entrada" ADD CONSTRAINT "detalle_entrada" FOREIGN KEY ("id_entrada") REFERENCES "entrada" ("id");

ALTER TABLE "detalle_entrada" ADD CONSTRAINT "detalle_entrada_producto" FOREIGN KEY ("id_producto") REFERENCES "producto" ("id");

ALTER TABLE "detalle_carrito" ADD CONSTRAINT "detalle_carrito" FOREIGN KEY ("id_carrito") REFERENCES "carrito" ("id");

ALTER TABLE "detalle_carrito" ADD CONSTRAINT "detalle_carrito_producto" FOREIGN KEY ("id_producto") REFERENCES "producto" ("id");

-- PEDIDO
ALTER TABLE "pedido" ADD CONSTRAINT "pedido_estado" FOREIGN KEY ("id_estado_pedido") REFERENCES "estado_pedido" ("id");

ALTER TABLE "pedido" ADD CONSTRAINT "pedido_entrega" FOREIGN KEY ("id_tipo_entrega") REFERENCES "tipo_entrega" ("id");

ALTER TABLE "pedido" ADD CONSTRAINT "pedido_pago" FOREIGN KEY ("id_metodo_pago") REFERENCES "metodo_pago" ("id");

ALTER TABLE "pedido" ADD CONSTRAINT "pedido_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id");

ALTER TABLE "detalle_pedido" ADD CONSTRAINT "detalle_pedido" FOREIGN KEY ("id_pedido") REFERENCES "pedido" ("id");

-- PEDIDO FIN

ALTER TABLE "detalle_pedido" ADD CONSTRAINT "detalle_pedido_producto" FOREIGN KEY ("id_producto") REFERENCES "producto" ("id");

ALTER TABLE "comprobante" ADD CONSTRAINT "comprobante_tipo_comprobante" FOREIGN KEY ("id_tipo_comprobante") REFERENCES "tipo_comprobante" ("id");